import Head from 'next/head';
import Image from 'next/image';
import { Inter } from 'next/font/google';
import styles from '@/styles/Home.module.css';
import { Button, Input, QRCode, Space } from 'antd';

const inter = Inter({ subsets: ['latin'] });

export default function Home() {
  return (
    <>
      <Head>
        <title>TOTP Macropay</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.main} ${inter.className}`}>
        <Space direction="vertical" align="center">
          <QRCode
            value={
              'otpauth://totp/Macropay%20Financing%3A2FA%20Huella?secret=HBJTSWC5I4XTSW3PII3TSXRMJ5GVEWCB'
            }
            size={300}
          />
          <Space.Compact style={{ width: '100%' }}>
            <Input defaultValue="000000" />
            <Button type="primary">Validar</Button>
          </Space.Compact>
        </Space>
      </main>
    </>
  );
}

